version: "3"

volumes: 
  - MONGODB_DATA : {} 
  - MONGODB_LOGS : {}
  - ELASTICSEARCH_DATA: {}
  - ELASTICSEARCH_LOGS: {}
  - ELASTICSEARCH_LOG_CONFIG: "./elasticsearch/logging.yml"
  - REDIS_MASTER_DATA : {}
  - REDIS_SLAVE_DATA : {}
  - REDIS_LOGS : {}
  - POSTGRES_DATA: {}


services: 
  mongo3:
    hostname: mongo3
    image: mongo:3.0.6
    container_name: mongo-rs3
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest", "--httpinterface" ]
    ports:
      - "27019:27017"
      - "28019:28017"
    restart: always


  mongo2:
    hostname: mongo2
    image: mongo:3.0.6
    container_name: mongo-rs2
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest", "--httpinterface" ]
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: always


  mongo1:
    hostname: mongo1
    image: mongo:3.0.6
    container_name: mongo-rs1
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest", "--httpinterface" ]
    ports:
      - "27017:27017"
      - "28017:28017"
    depends_on:
      - mongo2
      - mongo3
    restart: always

  # This configures the MongoDB replicaset
  mongosetup:
    image: mongo:3.0.6
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]


  elasticsearch:
    hostname: elasticsearch
    image: stabenfeldt/elasticsearch-marvel
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      # - =./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logging.yml:/etc/elasticsearch/logging.yml
    restart: always


  elasticsearch-hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch_hq
    ports:
      - "5000:5000"
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch



  ###################################################################
  # Make sure you include either mongo-connector OR transporter.
  #
  #

  # mongo-connector
  # https://github.com/10gen-labs/mongo-connector
  #connector:
  #  image: python:latest
  #  depends_on:
  #    - mongo1
  #    - mongo2
  #    - mongo3
  #    - elasticsearch:elasticsearch
  #  volumes:
  #    - ./scripts:/scripts
  #  entrypoint: [ "/scripts/mongo-connector.sh" ]


  # Transporter
  #
  # https://github.com/compose/transporter
  # https://www.compose.io/articles/transporter-driving-part-one/
  transporter:
    image: golang:1.5
    container_name: mongolastic-transporter
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - elasticsearch
    volumes:
      - ./transporter:/transporter
      - ./scripts:/scripts
    entrypoint: [ "/transporter/run.sh" ]
    restart: always


  # Make sure ES does not rellocate it's shards when it has low disk space.
  disabledisktreshold:
    image: mongo:3.0.6
    depends_on:
      - elasticsearch
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/disable-disk-treshold.sh" ]


  # Verify reading and writing
  # Run 'docker logs -f mongolastic-verify' to see what it outputs.
  verify:
    image: mongo:3.0.6
    container_name: mongolastic-verify
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - elasticsearch
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/query.sh" ]
